# Generated by Django 4.1 on 2023-04-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
