# Generated by Django 4.1 on 2023-04-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reading_history',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wishlist',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
