# Generated by Django 4.1 on 2023-05-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libsystem', '0005_book_description_alter_book_ratings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
    ]
